name: Publish Python 🚀

on:
  push:
    tags:
      - 'v*.*.*'       # triggers on semver-style tags, e.g. v1.0.0

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      # 1. Check out your code
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      # 3. Install build tools
      - name: Install build dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build twine

      # 4. Build your package
      - name: Build distribution archives
        run: python -m build

      # 5. Publish to PyPI
      - name: Publish to PyPI
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
        run: python -m twine upload dist/*
